$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1408153554572.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"39338edfd6224fffaf2bec305ef20a50",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d988848920de4957b0915b99b29e8dd0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":0},
            "size":{
              "width":410,
              "height":700}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7e4487582f64a9ab12ccd153e8c1453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10,
                  "y":0},
                "size":{
                  "width":410,
                  "height":700}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"34a86aff328446cfa0b49fc4178c52ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":20,
              "y":210},
            "size":{
              "width":110,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c98fc53d60c642eea9b60f2ff32e0cc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":20,
                  "y":210},
                "size":{
                  "width":110,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我要存款",
                      "target":{
                        "targetType":"page",
                        "url":"我要存款.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70a9ea3b42e54182a0cdf4d5c5a1ff0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":140,
              "y":210},
            "size":{
              "width":110,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1967bc4f943a48ff9171650b4092022e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":140,
                  "y":210},
                "size":{
                  "width":110,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 申请贷款",
                      "target":{
                        "targetType":"page",
                        "url":"申请贷款.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8934c640c94d4ad7bc3a059039286d9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":260,
              "y":210},
            "size":{
              "width":110,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f3d1c2f8c054ba1b08a5236fade711e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":260,
                  "y":210},
                "size":{
                  "width":110,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 委托放贷",
                      "target":{
                        "targetType":"page",
                        "url":"委托放贷.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0d008d392254bfb8318215e4030cbec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":20,
              "y":330},
            "size":{
              "width":110,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0e1580364454d278c9d733851762e40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":20,
                  "y":330},
                "size":{
                  "width":110,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 村行动态",
                      "target":{
                        "targetType":"page",
                        "url":"村行动态.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cd273802fdf4004bc9eb79e18f23797",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":140,
              "y":330},
            "size":{
              "width":110,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cd7f4e10fc042609acebe55a874364b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":140,
                  "y":330},
                "size":{
                  "width":110,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 行业要闻",
                      "target":{
                        "targetType":"page",
                        "url":"行业要闻.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4781e3e3ba6042fabe065d6a9c00d8a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":260,
              "y":330},
            "size":{
              "width":110,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6e8bcf8818e435a99a88c0fba202b14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":260,
                  "y":330},
                "size":{
                  "width":110,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 政策速递",
                      "target":{
                        "targetType":"page",
                        "url":"政策速递.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48b2c8ecdd4947829d800149ea66e820",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":20,
              "y":440},
            "size":{
              "width":110,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9151366af602427da9ceee1643c830c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":20,
                  "y":440},
                "size":{
                  "width":110,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 村行名录",
                      "target":{
                        "targetType":"page",
                        "url":"村行名录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c2570c13ea94fa4b84de2c2e10c4b03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":140,
              "y":440},
            "size":{
              "width":110,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e052d5017844460b7927f524c538940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":140,
                  "y":440},
                "size":{
                  "width":110,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 村行注册",
                      "target":{
                        "targetType":"page",
                        "url":"村行注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd6ca0bfb2a74295903dae89b86f9792",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":260,
              "y":440},
            "size":{
              "width":110,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd6b9d3fa1c447cea777f59a9be1a2c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":260,
                  "y":440},
                "size":{
                  "width":110,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人注册",
                      "target":{
                        "targetType":"page",
                        "url":"个人注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d988848920de4957b0915b99b29e8dd0":{
      "scriptId":"u0"},
    "c7e4487582f64a9ab12ccd153e8c1453":{
      "scriptId":"u1"},
    "34a86aff328446cfa0b49fc4178c52ce":{
      "scriptId":"u2"},
    "c98fc53d60c642eea9b60f2ff32e0cc5":{
      "scriptId":"u3"},
    "70a9ea3b42e54182a0cdf4d5c5a1ff0a":{
      "scriptId":"u4"},
    "1967bc4f943a48ff9171650b4092022e":{
      "scriptId":"u5"},
    "8934c640c94d4ad7bc3a059039286d9d":{
      "scriptId":"u6"},
    "9f3d1c2f8c054ba1b08a5236fade711e":{
      "scriptId":"u7"},
    "a0d008d392254bfb8318215e4030cbec":{
      "scriptId":"u8"},
    "d0e1580364454d278c9d733851762e40":{
      "scriptId":"u9"},
    "7cd273802fdf4004bc9eb79e18f23797":{
      "scriptId":"u10"},
    "1cd7f4e10fc042609acebe55a874364b":{
      "scriptId":"u11"},
    "4781e3e3ba6042fabe065d6a9c00d8a2":{
      "scriptId":"u12"},
    "e6e8bcf8818e435a99a88c0fba202b14":{
      "scriptId":"u13"},
    "48b2c8ecdd4947829d800149ea66e820":{
      "scriptId":"u14"},
    "9151366af602427da9ceee1643c830c3":{
      "scriptId":"u15"},
    "9c2570c13ea94fa4b84de2c2e10c4b03":{
      "scriptId":"u16"},
    "7e052d5017844460b7927f524c538940":{
      "scriptId":"u17"},
    "cd6ca0bfb2a74295903dae89b86f9792":{
      "scriptId":"u18"},
    "bd6b9d3fa1c447cea777f59a9be1a2c3":{
      "scriptId":"u19"}}});