$axure.loadCurrentPage({
  "url":"政策速递.html",
  "generationDate":new Date(1408153554756.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0b637eb0e98a4db5a63938d6bb4200ff",
    "type":"Axure:Page",
    "name":"政策速递",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6e0557535f674220a3272402aa25c40f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":400,
              "height":700}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0f3aad63366418e91d5efdc6e35d06b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":400,
                  "height":700}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 详情页",
                      "target":{
                        "targetType":"page",
                        "url":"详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/政策速递/u0.png"}},
{
          "id":"9a4974811e2b4a569888d7b9c35fa0e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f3344f03a3341c7a606dbd46cb87d89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6e0557535f674220a3272402aa25c40f":{
      "scriptId":"u0"},
    "f0f3aad63366418e91d5efdc6e35d06b":{
      "scriptId":"u1"},
    "9a4974811e2b4a569888d7b9c35fa0e0":{
      "scriptId":"u2"},
    "9f3344f03a3341c7a606dbd46cb87d89":{
      "scriptId":"u3"}}});